trigger:
- master
- develop

resources:
  containers:
  - container: linux
    image: dockfool/cake-docker:latest

jobs:
- job: build
  pool:
    vmImage: 'ubuntu-16.04'
  container: linux
  steps:
  - bash: bash build.sh
