trigger:
- master
- develop

resources:
  containers:
  - container: linux
    image: cakebuild/cake:2.1-sdk-mono

jobs:
- job: build
  pool:
    vmImage: 'ubuntu-16.04'
  container: linux
  steps:
  - bash: bash build.sh
