trigger:
- master
- develop

resources:
  containers:
  - container: linux
    image: mcr.microsoft.com/dotnet/core/sdk:2.2

jobs:
- job: build
  pool:
    vmImage: 'ubuntu-16.04'
  container: linux
  steps:
  - bash: |
      - dotnet tool install -g Cake.Tool
      - export PATH=$PATH:$HOME/.dotnet/tools
      - dotnet cake build.cake
